# Generated by Django 3.1.5 on 2021-01-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0004_auto_20210130_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='lastUpdated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
