# Generated by Django 3.1.5 on 2021-01-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0006_strategyoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='lastUpdated',
            field=models.DateTimeField(null=True),
        ),
    ]
