# Generated by Django 3.1.5 on 2021-01-30 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0007_auto_20210130_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='lastUpdated',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
