# Generated by Django 3.1.5 on 2021-01-30 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0008_auto_20210130_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='lastUpdated',
            new_name='nextUpdate',
        ),
    ]
