# Generated by Django 3.1.5 on 2021-01-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0009_auto_20210130_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyoperation',
            name='type',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
