# Generated by Django 3.1.5 on 2021-01-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0010_strategyoperation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyoperation',
            name='timestampOpen',
            field=models.DateTimeField(),
        ),
    ]
