# Generated by Django 3.1.5 on 2021-01-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0011_auto_20210131_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyoperation',
            name='beneficio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='strategyoperation',
            name='buyAmount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='strategyoperation',
            name='sellAmount',
            field=models.FloatField(null=True),
        ),
    ]
