# Generated by Django 3.1.5 on 2021-01-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0012_auto_20210131_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategystate',
            name='isRunning',
            field=models.BooleanField(null=True),
        ),
    ]
