# Generated by Django 3.1.5 on 2021-02-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0013_strategystate_isrunning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='cryptoTimeframeADX',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='cryptoTimeframeDI',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
