# Generated by Django 3.1.5 on 2021-02-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0014_auto_20210201_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='accion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='adx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='beneficioTotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='currentRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='diffDI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Hold'), (1, 'Preoper'), (2, 'Oper'), (3, 'Precierre')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='maxCurrentRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='minusDI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='operID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='plusDI',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
