# Generated by Django 3.1.5 on 2021-02-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0016_auto_20210202_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyoperation',
            name='reason',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Hold'), (1, 'Preoper'), (2, 'Oper'), (3, 'Cooldown')], default=0, null=True),
        ),
    ]
