# Generated by Django 3.1.5 on 2021-02-05 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0017_auto_20210205_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategystate',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
