# Generated by Django 3.1.5 on 2021-02-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0018_auto_20210205_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategystate',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
