# Generated by Django 3.1.5 on 2021-02-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0019_auto_20210205_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyoperation',
            name='reason',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='strategyoperation',
            name='timestampOpen',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
