# Generated by Django 3.1.5 on 2021-02-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0020_auto_20210205_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategyoperation',
            name='reason',
        ),
    ]
