# Generated by Django 3.1.5 on 2021-02-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0021_remove_strategyoperation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyoperation',
            name='reasonClose',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
