# Generated by Django 3.2.8 on 2021-11-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0022_strategyoperation_reasonclose'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='adxClose',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='bet',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='comentarios',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='ema',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='placedPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='protectedTrade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strategystate',
            name='ema',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='beneficioTotal',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='isRunning',
            field=models.BooleanField(default=False),
        ),
    ]
