# Generated by Django 3.2.8 on 2021-11-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0023_auto_20211109_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
