# Generated by Django 3.2.8 on 2021-11-12 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0024_alter_strategy_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='comentarios',
            new_name='comments',
        ),
    ]
