# Generated by Django 3.2.8 on 2021-12-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0026_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='cooldownUntil',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='strategyoperation',
            name='beneficio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategyoperation',
            name='reasonClose',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='strategyoperation',
            name='sellAmount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategyoperation',
            name='timestampClose',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
