# Generated by Django 3.2.8 on 2021-12-27 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0027_auto_20211226_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='cooldownUntil',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
