# Generated by Django 3.2.8 on 2023-12-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0028_alter_strategy_cooldownuntil'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='operSymbolBingx',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
