# Generated by Django 3.2.8 on 2023-12-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0029_strategy_opersymbolbingx'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='operIDclose',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
