# Generated by Django 3.2.8 on 2023-12-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0030_strategy_operidclose'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyoperation',
            name='operIDClose',
            field=models.IntegerField(null=True),
        ),
    ]
