# Generated by Django 3.2.8 on 2023-12-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0031_strategyoperation_operidclose'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='currentProfit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
