# Generated by Django 3.2.8 on 2024-01-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0033_auto_20240112_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyoperation',
            name='profit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
