# Generated by Django 3.2.8 on 2024-01-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0034_strategyoperation_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='sleep',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='takeProfitCurrent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
