# Generated by Django 3.2.8 on 2024-01-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0037_strategystate_currentprofit'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='ema100',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='ema20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategystate',
            name='ema100',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='strategystate',
            name='ema20',
            field=models.FloatField(null=True),
        ),
    ]
