# Generated by Django 3.2.8 on 2024-01-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0039_alter_strategy_ticksymbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='recommendMA',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
