# Generated by Django 3.2.8 on 2024-01-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0040_strategy_recommendma'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategystate',
            name='recommendMA',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
