# Generated by Django 3.2.8 on 2024-01-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0041_strategystate_recommendma'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='recommendMA240',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='strategystate',
            name='recommendMA240',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
