# Generated by Django 3.2.8 on 2024-01-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0042_auto_20240121_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='inError',
            field=models.BooleanField(default=False),
        ),
    ]
