# Generated by Django 3.2.8 on 2024-02-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0043_strategy_inerror'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='inError',
        ),
        migrations.AddField(
            model_name='strategy',
            name='leverage',
            field=models.IntegerField(default=4),
        ),
    ]
