# Generated by Django 3.2.8 on 2024-03-02 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0047_auto_20240302_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='proccessEnabled',
        ),
    ]
