# Generated by Django 3.2.8 on 2024-03-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0048_remove_profile_proccessenabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='configMaxBet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
