# Generated by Django 3.2.8 on 2024-03-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0049_alter_profile_configmaxbet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='configTest',
            field=models.BooleanField(default=False),
        ),
    ]
