# Generated by Django 3.2.8 on 2024-03-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0050_profile_configtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategystate',
            name='stopLossCurrent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
