# Generated by Django 3.2.8 on 2024-11-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0052_auto_20241117_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='configGlobalTPWakeUp',
            field=models.DateTimeField(null=True),
        ),
    ]
