# Generated by Django 3.2.8 on 2024-12-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0053_profile_configglobaltpwakeup'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='configLegacyGraph',
            field=models.BooleanField(default=True),
        ),
    ]
