# Generated by Django 4.2.17 on 2025-09-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0054_profile_configlegacygraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='atr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategystate',
            name='atr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]