# Generated by Django 4.2.17 on 2025-09-04 10:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0055_strategy_atr_strategystate_atr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='bars_in_trade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='day_pnl',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9),
        ),
        migrations.AddField(
            model_name='strategy',
            name='last_trade_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='partial_done',
            field=models.BooleanField(default=False),
        ),
    ]