# Generated by Django 4.2.17 on 2025-09-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0056_strategy_bars_in_trade_strategy_day_pnl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategystate',
            name='takeProfitCurrent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]