# Generated by Django 4.2.17 on 2025-09-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0057_strategystate_takeprofitcurrent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='diffDI',
        ),
        migrations.RemoveField(
            model_name='strategystate',
            name='diffDI',
        ),
    ]
