# Generated by Django 4.2.17 on 2025-09-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT', '0058_remove_strategy_diffdi_remove_strategystate_diffdi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='limitBuy',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='limitSell',
            field=models.IntegerField(default=-25),
        ),
    ]
